version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    networks:
      kiv-pia:
        ipv4_address: 10.5.0.5
    environment:
      MYSQL_DATABASE: 'bikesharing'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "TZ=Europe/Prague"
    networks:
      kiv-pia:
        ipv4_address: 10.5.0.7
    depends_on:
      - db

volumes:
  my-db:

networks:
  kiv-pia:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16